name: Docker Build and Push

on:
  push:
    branches:
      - dev # or any other branch you wish to have the automation run on
  pull_request:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create .env.local file
        run: |
          echo "$UNSAGED_ENV_LOCAL" > ./apps/unsaged/.env.local
        env:
          UNSAGED_ENV_LOCAL: ${{ secrets.UNSAGED_ENV_LOCAL }}
          
      - name: Install dependencies for unsaged app
        run: |
          cd apps/unsaged
          pnpm install
          cd ../../
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub (or your preferred registry)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./apps/unsaged/Dockerfile
          push: true
          tags: bpvarsity/unsaged:latest

      - name: Build and push Docker image with version
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: bpvarsity/unsaged:${{ github.ref_name }}
